### ISSUE TITLE
How to use Roswell to run code from my GitHub repo?

### ISSUE THREAD

**Issue by MatthewRock** [roswell/roswell#225]
Hi!

I am trying to use Roswell to install various CL implementations and to test my library that I have developed. However, Roswell's QL can't seem to find my library. I'm using Travis CI.

The library can be found [here](https://github.com/MatthewRock/cl-sandbox/).

Basically, here's what I do:

- Install Roswell using your script for CI.
- use `ros install MatthewRock/cl-sandbox` to install my library
- use `ros install fiveam` to install fiveam
- use my local ros script(essentially a main with quickload and asdf call to test my library)

I can't seem to figure out why, but this does not work.

Here's what I have tried:
- Linking my repository manually to the ~/.roswell/local-projects/ ; did not work.
- Linking my repository manually to the ~/.roswell/quicklisp/local-projects/ ; did not work.

Each time I'm getting QUICKLISP-CLIENT:SYSTEM-NOT-FOUND error.

What am I doing wrong?

**Comment by snmsts** [comment]
Thank you for your report.

What developers want to report is how we can reproduce your bug or phenomenon to fix.

- what kind of os or cpu or anything related your bug. 
- expression is also problem. what do you mean by "Install Roswell using your script for CI." We don't encourage users to use it for non-CI environment.
- Why don't you share your local ros script?
- Why no log in this report?

Those information are missing.
If you think we can notice what you expected by little information, that expectation is too much.
I feel sorry that I can say about it for now is only "I don't know".

**Comment by guicho271828** [comment]
Your ros scripts should be in the `roswell/` subdirectory of your repo.

**Comment by guicho271828** [comment]
ok, I see you have your scripts in `roswell` but it is in `travis-installation` branch.
`ros install MatthewRock/cl-sandbox/travis-installation` seems working fine.
@snmsts , however I noticed that the ros scripts are not recognized and they are not copied to `~/.roswell/bin`. I also noticed that if I run 
    ros install MatthewRock/cl-sandbox ; ros install MatthewRock/cl-sandbox/travis-installation
then the new branch is not checked out.

**Comment by guicho271828** [comment]
BTW I'm holding myself back from doing this fix; If I do, I would end up refactoring the entire code (which will eventually be reverted...).

**Comment by guicho271828** [comment]
BTW2 I understand the language issue but that sounds a bit harsh (you are a nice guy in Japanese I know). I sent a PR regarding this #226

**Comment by snmsts** [comment]
I admit.

**Comment by MatthewRock** [comment]
Thank you for your answers.

I hoped that providing links would be a nice way to not clutter topic at hand and provide you with enough details, but here it comes.

Example of two last builds, one when I try to get correct branch, one where not(all running ABCL installed by ros CI script):

Here is my Travis CI .yml script:

```
language: lisp
sudo: false

env:

  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell

  matrix:
    - LISP=abcl-bin
    - LISP=allegro
    - LISP=sbcl
    - LISP=cmu-bin
    - LISP=ccl-bin
    - LISP=clisp
    - LISP=ecl

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-7-jre

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp


install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  - ros install fiveam
  - ros install MatthewRock/cl-sandbox/travis-installation
script:
  - ros -s cl-sandbox -e "(asdf:test-system 'cl-sandbox)"

```

And here we've got roswell file:
```
#!/bin/sh
#|-*- mode:lisp -*-|#
#| Common Lisp sandbox package for testing out stuff.
exec ros -Q -- $0 "$@"
|#

(defun main (&rest argv)
  (ql:quickload '(:cl-sandbox) :silent t)
  (asdf:test-system 'cl-sandbox))
;;; vim: set ft=lisp lisp:
![screenshot-20170311 224114](https://cloud.githubusercontent.com/assets/1909226/23826770/2200fb62-06a4-11e7-8042-ef694d546e6b.png)
![screenshot-20170311 224243](https://cloud.githubusercontent.com/assets/1909226/23826771/2204b05e-06a4-11e7-8f19-aaf25bb2c446.png)

Screenshots are attached as files.

```
