### ISSUE TITLE
Support installing 32bit sbcl/sbcl-bin on 64bit linux

### ISSUE THREAD

**Issue by 3b** [roswell/roswell#417]
For CI, I'd like to test some code on both 32 and 64bit lisps.

 `curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh` works for `LISP=ccl32`, but `LISP=sbcl32` and `LISP=clisp32` error.

## Environment

Github actions `ubuntu-latest` 

## How to reproduce the issue

```yaml
    - name: install roswell
      env:
       LISP: sbcl32 # or clisp32
      run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh

```

## Expected behavior

successful install of 32bit sbcl or clisp

## Actual result

```
Roswell has been installed.
Installing sbcl32...
Installing sbcl-bin...

...

Making core for Roswell...
'sbcl32' is not a valid target for 'install' -- It should be a name of either:
+ a quicklisp-installable system
+ a common lisp installation 
##[error]Process completed with exit code 1.
```
